Anakondaの新版で遭遇したPyInstallerでの問題と対策

（その１）
PyInstaller実行時に「再起呼び出しが最大レベルを超えた」というメッセージが出て処理が止まる。
→対策はspecファイルの先頭に次の2行を追加してPI.batを動かす。
import sys
sys.setrecursionlimit(5000)


（その２）（解決ずみ）
PyInstaller実行時に次のエラーメッセージが表示され処理が止まる。
ーーーー前略
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\shush_000\anaconda35\lib\site-packages\PyInstaller\hooks\hook-PyQt5.QtGui.py", line 11, in <module>
    hiddenimports, binaries, datas = add_qt5_dependencies(__file__)
  File "c:\users\shush_000\anaconda35\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 514, in add_qt5_dependencies
    more_binaries = qt_plugins_binaries(plugin, namespace=namespace)
  File "c:\users\shush_000\anaconda35\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 132, in qt_plugins_binaries
    pdir = qt_plugins_dir(namespace=namespace)
  File "c:\users\shush_000\anaconda35\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 117, in qt_plugins_dir
    """.format(namespace, ", ".join(paths)))
Exception:
            Cannot find existing PyQt5 plugin directories
            Paths checked: C:/Miniconda3/conda-bld/qt_1535195524645/_h_env/Library/plugins
ーーーーーここまで
どうやら、Qt5（PyQt5.QtCore.QLibraryInfo）がQLibraryInfo.PluginsPathの問合せに対して、
C:/Miniconda3/conda-bld/qt_1535195524645/_h_env/Library/plugins
という意味のないパスを返すことが問題のようである。
→対策は以下。
これを処理しているのは、
C:\Users\shush_000\Anaconda35\Lib\site-packages\PyInstaller\utils\hooks\qt.py
というスクリプト。
これの95行目を正しいパスを含むように書き換えてやれば成功しそう。正しいパスはこれではないか。
C:/Users/shush_000/Anaconda35/Library/plugins

OK。通った。
この件（その２）については、ANACONDAのディストリビューションを「Anaconda3-2019.07」に更新したところ、発生しなかった。ANACONDAが修正された模様。2019/8/24


（その３）
Version 1.4.1 のコンパイルを行ったところ、次のメッセージが出てPyInstallerが異常終了した。
----------------------------------------
'utf-8' codec can't decode byte 0x83 in position 130: invalid start byte
These are the bytes around the offending byte:
----------------------------------------
トレースバックの最後は次の行。
  File "c:\users\shush\anaconda3\lib\site-packages\PyInstaller\compat.py", line 427, in exec_command
    out = out.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 130: invalid start byte
問題の行（compat.py の line 427）を次のどちらかに書き換えると大丈夫らしい。
    out = out.decode(encoding, errors='ignore')
    out = out.decode(encoding, "replace")
参考情報はこちら。
(1) https://qiita.com/pocket_kyoto/items/80a1ac0e46819d90737f
(2) https://stackoverflow.com/questions/47692960/error-when-using-pyinstaller-unicodedecodeerror-utf-8-codec-cant-decode-byt
参考情報(2)のコードを見ると、1.4.1で追加したコード（matplotlib.use('Qt5Agg')）が入っている。この関係かもしれない。
compat.py に後者の修正を行ったところ、コンパイルに成功した。
（2019/9/27）




2021/7/19
Anaconda3を最新版（3.8）に更新。Pythonは3.8.8になった
conda でPyInstaller 3.6をインストール

（問題１）
SSVG1.5.0をコンパイルして実行すると次のエラーが出る。

C:\Users\Public\Downloads\SSVG>ssvg.exe
INTEL MKL ERROR: 指定されたモジュールが見つかりません。 mkl_intel_thread.1.dll.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.1.dll.

トライ１：mkl_intel_thread.1.dll をコンパイル後のSSVGにコピーした：メッセージも出さず異常終了。

.specファイルに以下の行を加える。ソースはこちら。https://stackoverflow.com/questions/35478526/pyinstaller-numpy-intel-mkl-fatal-error-cannot-load-mkl-intel-thread-dll　ただし、mkl_で始まるファイルをぜんぶコピーするように修正してある。

mkl_dlls = [
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_avx.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_avx2.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_avx512.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_blacs_ilp64.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_blacs_intelmpi_ilp64.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_blacs_intelmpi_lp64.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_blacs_lp64.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_blacs_mpich2_ilp64.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_blacs_mpich2_lp64.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_blacs_msmpi_ilp64.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_blacs_msmpi_lp64.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_cdft_core.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_core.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_def.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_intel_thread.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_mc.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_mc3.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_msg.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_pgi_thread.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_rt.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_scalapack_ilp64.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_scalapack_lp64.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_sequential.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_tbb_thread.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_vml_avx.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_vml_avx2.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_vml_avx512.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_vml_cmpt.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_vml_def.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_vml_mc.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_vml_mc2.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\mkl_vml_mc3.1.dll', '.'),
 ('C:\\Users\\shush\\anaconda3\\envs\\ssvg\\Library\\bin\\libiomp5md.dll', '.')]

あと、この修正も。
a = Analysis(['yourpythonappnamehere.py'],
             pathex=['C:\\Users\\...\\Documents\\...'],
             binaries=mkl_dlls,
             datas=None,
             ....

（問題２）
実行すると次のエラーが出る。
ModuleNotFoundError: No module named 'scipy.spatial.transform._rotation_groups'
[11128]

Scipyの問題らしい。
.specファイルの hiddenimportに ’scipy.spatial.transform._rotation_groups’ を与えることで解決した。

（問題３）
実行すると次のエラーが出る。matplotlibで。
NameError: name 'defaultParams' is not defined
matplotlibを3.2.2に戻すと解決するという記事あり。SSVG環境だけ3.2.2に戻す。
解決した。



